name = "MakeTeams"
uuid = "db8ae261-cbdc-45aa-a9f2-f36c25d7a07d"
authors = ["Nicholas Stone <stone.nicholas@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
